#!/bin/bash

# BASE OPTIONS
if [ ! -z $1 ] 
then 
    : 
    SKETCHFILE="$1"
else
    : 
    echo ""
    echo "no sketchfile provided"
    echo ""
    echo ""
    echo "SYNTAX :"
    echo ""
    echo ". sketchoptim.sh path/to/sketchfile max_width_in_px"
    echo ""
    echo "example :"
    echo ". sketchoptim.sh mysketchfile.sketch 1400"
    return
fi

if [ ! -z $2 ] 
then 
    : 
    MAXWIDTH="$2"
else
    : 
    MAXWIDTH=1440
    echo ""
    echo "No max width provided. Defaulting to 1440px."
    echo ""
fi

if [ -f "$SKETCHFILE" ]
then
  echo "File exists!"
  echo ""
  echo "Export Start"
  echo ""
  echo "Creating temp directory"
  cd ~
  mkdir __temp_sketchoptimizer
  cd __temp_sketchoptimizer
  cp "$SKETCHFILE" .
  open .
  THEFILE=$(basename "$SKETCHFILE")
  OUTPUT="filename : $SKETCHFILE • Max width $MAXWIDTH"
  say "processing $THEFILE"
  unzip "$THEFILE"
  rm "$THEFILE"
  cd images
  say "Optimizing assets"
  sips -Z "$MAXWIDTH" *
  cd ..
  say "creating optimized sketchfile"
  zip -r "optimized.$THEFILE" *
  mv "optimized.$THEFILE" ~/Desktop
  cd ..
  rm -rf __temp_sketchoptimizer
  say "optimized file is on your desktop!"
  return
  # mkdir _temp
  # # cp "$SKETCHFILE" "_temp/$SKETCHFILE"
  # # echo "Uncompressing assets"
  # # cd _temp
  # # unzip "$SKETCHFILE"
  # # rm "$SKETCHFILE"
  # # cd images
  # # echo "Optimizing assets"
  # # sips -Z "$MAXWIDTH" *
  # # cd ..
  # # echo "creating optimized sketchfile"
  # # zip -r "optimized.$SKETCHFILE" *
  # # cd ..
  # # mv "_temp/optimized.$SKETCHFILE" "optimized.$SKETCHFILE"
  # # echo "deleting temp files"
  # # rm -rf _temp
  # # echo "Success!!"
else
  echo "File not found."
  echo ""
  return
fi


# FILESIZE="$2"
echo " $SKETCHFILE $MAXWIDTH"

